version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 858656722878.dkr.ecr.eu-north-1.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - echo Building Docker image...
      - docker build -t brain-tasks-app:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - docker tag brain-tasks-app:$CODEBUILD_RESOLVED_SOURCE_VERSION 858656722878.dkr.ecr.eu-north-1.amazonaws.com/brain-tasks-app:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker tag brain-tasks-app:$CODEBUILD_RESOLVED_SOURCE_VERSION 858656722878.dkr.ecr.eu-north-1.amazonaws.com/brain-tasks-app:latest

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push 858656722878.dkr.ecr.eu-north-1.amazonaws.com/brain-tasks-app:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push 858656722878.dkr.ecr.eu-north-1.amazonaws.com/brain-tasks-app:latest
      - echo Updating kubeconfig...
      - aws eks update-kubeconfig --region eu-north-1 --name brain-tasks-cluster
      - echo Deploying application to EKS...
      - kubectl apply -f deployment.yaml
      - kubectl apply -f service.yaml
      - kubectl rollout status deployment/brain-tasks-app
      - echo Deployment completed on `date`

artifacts:
  files:
    - '**/*'
