apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: brain-tasks-cluster
  region: eu-north-1
  version: "1.34"

vpc:
  nat:
    gateway: Disable

managedNodeGroups:
  - name: brain-tasks-nodes
    instanceType: t3.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
